Do not package build ids to avoid error with ondemand-gems having multiple versions installed:
Error: Transaction check error:
  file /usr/lib/.build-id/45/6fc61ed5006038c2e923146f186b243d304c05 from install of ondemand-gems-1.7.3-1.7.3-1.el8.x86_64 conflicts with file from package ondemand-gems-1.7.2-1.7.2-1.el8.x86_64
  file /usr/lib/.build-id/71/e4fc4d9cbd24601f899882c010f32ec5bddd4c from install of ondemand-gems-1.7.3-1.7.3-1.el8.x86_64 conflicts with file from package ondemand-gems-1.7.2-1.7.2-1.el8.x86_64
  file /usr/lib/.build-id/7e/8f3b316f237075d3a293e634366c4c641c23ad from install of ondemand-gems-1.7.3-1.7.3-1.el8.x86_64 conflicts with file from package ondemand-gems-1.7.2-1.7.2-1.el8.x86_64